-- Session 56 — NHL "results vs. process" per-player feature.
-- Run this in the Supabase SQL editor. This file is a reference copy, not
-- executed by any pipeline code (this repo has no migration tooling --
-- schema changes are applied directly in Supabase, same as every existing
-- pwhl_*/team_seasons/player_seasons column addition).

-- ── Item 1: on-ice GF% (5v5) + results-vs-process differential.
-- Populated by moneypuck.py::run()'s existing per-player pass (on_ice_gf_pct()
-- reads MoneyPuck's OnIce_F_goals/OnIce_A_goals, sitting right next to the
-- OnIce_F_xGoals/OnIce_A_xGoals that ev_off_pct already reads).
--
-- Deliberately NOT adding a duplicate on-ice-xGF% column: player_seasons
-- already has ev_off_pct (on-ice xGF% at 5v5 -- see moneypuck.py::ev_off()),
-- which IS the "process" side of this pairing. results_vs_process_diff =
-- on_ice_gf_pct - ev_off_pct.
--
-- Both columns are NULL for any player under RESULTS_VS_PROCESS_MIN_GP (25,
-- see moneypuck.py) -- that's the single source of truth for the reliability
-- guardrail. eyewall-poller and the frontend should treat "column is null"
-- as "not enough games yet," not re-derive a GP threshold of their own.
alter table public.player_seasons
  add column on_ice_gf_pct numeric,
  add column results_vs_process_diff numeric;

-- ── Item 2: narrative blurb table, replacing the original plan to bolt a
-- second text column onto player_scouting. Keyed on (player_id, season,
-- team, narrative_type) so it can hold more than one blurb type later (e.g.
-- a future line-chemistry narrative) without another schema change --
-- narrative_type='results_vs_process' is the only value written this round.
-- Populated by ai_results_vs_process.py, same upsert-on-conflict shape as
-- ai_scouting.py's player_scouting writes.
create table public.player_narratives (
  id bigint generated by default as identity primary key,
  player_id integer not null,
  season integer not null,
  team text not null,
  narrative_type text not null,
  narrative_text text not null,
  generated_at timestamptz not null default now()
);

create unique index player_narratives_conflict_key
  on public.player_narratives (player_id, season, team, narrative_type);
